admin_email = "kerykeion.astrology@gmail.com"
debug = true
docs_url = "/docs"
redoc_url = "/redoc"
log_level = 10
secret_key_name = "X-RapidAPI-Proxy-Secret"

allowed_hosts = ['*']

allowed_cors_origins = ['*']